image: alpine/edge
packages:
  - go
  - scdoc
  - bmake
sources:
  - https://git.xenrox.net/~xenrox/hut
tasks:
  - build: |
      cd hut
      make
  - test: |
      cd hut
      go test ./...
  - gofmt: |
      cd hut
      test -z $(gofmt -l . | grep -v '^srht/.*/gql.go$')
  - build-bmake: |
      cd hut
      make clean
      bmake
