image: alpine/latest
packages:
  - go
  - scdoc
sources:
  - https://git.sr.ht/~emersion/hut
tasks:
  - build: |
      cd hut
      make
  - test: |
      cd hut
      go test ./...
  - gofmt: |
      cd hut
      test -z $(gofmt -l .)
